//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDTest.NorthwindCRUDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NorthwindCRUDService.IBasicCRUDservice")]
    public interface IBasicCRUDservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicCRUDservice/ListCustomers", ReplyAction="http://tempuri.org/IBasicCRUDservice/ListCustomersResponse")]
        System.Data.DataSet ListCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicCRUDservice/InsertCustomer", ReplyAction="http://tempuri.org/IBasicCRUDservice/InsertCustomerResponse")]
        bool InsertCustomer(string companyName, string contactName, string city, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicCRUDservice/EditCustomer", ReplyAction="http://tempuri.org/IBasicCRUDservice/EditCustomerResponse")]
        System.Data.DataSet EditCustomer(string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicCRUDservice/SaveCustomer", ReplyAction="http://tempuri.org/IBasicCRUDservice/SaveCustomerResponse")]
        bool SaveCustomer(string companyName, string contactName, string city, string country, string customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasicCRUDservice/DeleteCustomer", ReplyAction="http://tempuri.org/IBasicCRUDservice/DeleteCustomerResponse")]
        bool DeleteCustomer(string customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasicCRUDserviceChannel : CRUDTest.NorthwindCRUDService.IBasicCRUDservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasicCRUDserviceClient : System.ServiceModel.ClientBase<CRUDTest.NorthwindCRUDService.IBasicCRUDservice>, CRUDTest.NorthwindCRUDService.IBasicCRUDservice {
        
        public BasicCRUDserviceClient() {
        }
        
        public BasicCRUDserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasicCRUDserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicCRUDserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasicCRUDserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListCustomers() {
            return base.Channel.ListCustomers();
        }
        
        public bool InsertCustomer(string companyName, string contactName, string city, string country) {
            return base.Channel.InsertCustomer(companyName, contactName, city, country);
        }
        
        public System.Data.DataSet EditCustomer(string CustomerID) {
            return base.Channel.EditCustomer(CustomerID);
        }
        
        public bool SaveCustomer(string companyName, string contactName, string city, string country, string customerID) {
            return base.Channel.SaveCustomer(companyName, contactName, city, country, customerID);
        }
        
        public bool DeleteCustomer(string customerID) {
            return base.Channel.DeleteCustomer(customerID);
        }
    }
}
